sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: '001216'
  file:
    # 文件上传位置
    upload-dir: D:/AAAAAZZH/upload/
    access-path: /image/**
  redis:
    host: localhost
    port: 6379
    password: '001216'
    database: 0